include::../Header.adoc[]

== How to start with Willy

Before understanding how Willy works, it is helpful to drive around with it for a bit. 

To do this you could choose between autonomous driving, manual or through your hand movements.

== Start procedure

To get Willy up and running, the following procedure must be followed.

1.	Twist the red handle on the left side of Willy vertically. This is the switch for the central power circuit of Willy. Be aware of the red emergency button above the laptop. (This button enables the emergency brakes when pushed down)

2.	Charge the battery of Willy and the laptop. Both chargers can be found on or near Willy. Willy’s charging port can be found underneath the previously mentioned red handle. Willy can only be charged if the handle is positioned vertically. (You should be able to hear when Willy is turned on)

3.	Start the laptop.

4.	Open a terminal.

5.	Make your choice between manual, LEAP motion or autonomous driving. The explanation on how to use these modes will be explained below.

== Manual driving

Willy can be controlled manually with the PS2 controller. This is the procedure:

1.	Make sure the controller is plugged into Willy’s left USB port on the laptop.

2.	Open a terminal on the laptop.

3.	Enter the command: `startjoystick` in the terminal. 

4.	Open a new terminal.

5.	Enter the command: `startmotorcon` in the terminal.

6.	Press the PlayStation button in the center of the controller to turn it on. A red light should now burn on top of the controller. 
Whenever the controller is activated, the laptop’s touchpad might act weird.

7.	Disengage the emergency brakes. (By releasing the emergency button)

8.	Willy can now drive by moving the left joystick while holding the R1 button. There is some delay, so caution is necessary.

== Mapping
Before Willy can drive autonomously it is first necessary to map the environment. this is the procedure:

1.	At first you should make a backup of the database in which the 3D map is saved. ( if you want to keep this database. )
  
  o	Cd ~/.ros
  
  o	Make a copy of the rtabmap.db, otherwise it will remove the old database.
  
       Cp rtabmap.db BACKUP_FILE_NAME

2.	Now the mapping can start.
3.	Go to ~/Documents/willy
4.	Execute:  start-willy-mapping-kinect.sh

  o	This script will launch what is necessary to run a mapping session.
      
      	Rviz: To visualize what is going on during the creation of the map
      
      	Hector-mapping: This takes care of the 2D map, the costmap etc.
      
      	RTABmap: Takes care of creating a 3D map of the location.
      
      	Motorcontroller: this makes it possible to drive the robot around.
      
      
      	Joystick: This package makes it possible to drive the robot around with the PS3 controller.

5.	After launching the mapping script, there will be an Rviz window in which you can monitor what is being mapped.
   
   o	Now you can drive the robot around using the controller. (To see how the controller works take a look at chapter Manual driving the last steps.)
   
   o	After completing one round, check the map if it is bad try again, but if it is OK, the map can saved (To create a better map, drive around multiple times.)

6.	At first the Hector 2D map needs to be saved, open an empty terminal and run the following command: "rosrun map_server map_saver -f {name of save file}"
7.	After making sure the 2D map is saved, the 3D mapped can be saved as well. This can be done by CTRL+C in the terminal, where the bash script is launched from. This will save the 3D map to: ~/.ros/rtabmap.db


== Autonomous driving

Willy has the capability to drive autonomously. This is the procedure:

1.	Open a terminal.

2.	Enter the command: `startwilly` and enter the password.

3.	A new window opens called Rviz. This is used to control Willy and visualize its position.

4.	On this window you can see a map of T5.

5.	Disengage the emergency brakes. (By releasing the emergency button)

6.	In Rviz, set Willy’s pose estimate within the T5 environment.

7.	In Rviz, drag a destination arrow on the map. This will enable Willy to try and drive to the location autonomously.

== Leap motion control

Willy can be controlled with hand movements using the LEAP motion sensor . This is the procedure:

1.	Open a terminal.

2.	Enter the command `startleap`. 

3.	A few terminals will now open with the input that ROS gets from the LEAP controller.

4.	Disengage the emergency brakes. (By releasing the emergency button)

5.	Control Willy with hand movements(Roll and pitch). This might require some practice.
 

