include::../Header.adoc[]


IMPORTANT: This page should be updated to reflect the current state.

== Findings

This file contains all the things we have found while prototyping and may be usefull to other project groups

=== Software
- The motor controller is a device that is used to control the cmd_vel topic created by the
ros navigation stack. The ros navigation stack published geometry::Twist messages 
- ROS is complicated and difficult to learn. But if everything is setup just right, ROS makes it really easy 
to communicate between your hardware. 
- If you want to create files to start multiple projects? Do not use bash files. ROS can't handle bash files properly.
use ros launch files instead.
- The making of the DrivingController was a complex situation. That is because of the fact every ROS node has only one ROS nodehandler.
To make it possible to subscribe and advertise everywhere in the DrivingWilly code, we must send the nodehandler to every
subcontroller by using pointers. This request a detailed knowledge of C++ and ROS.
- The setup of the ROS navigation stack is difficult because of the fact that every robot is different.
A lot of components needs to be setup on your own. As example the move_base, the transformations and rotations
and the cmd_vel topic. 

=== Vision
- When the kinect is used together with the LIDAR for indoor navigation, the kinect can
not handle the fast scan frequency of the LIDAR which will cause the transform of the robot 
to become unknown. Then the robot will lost its orientation.
- The kinect cannot look further than 10 meters away. Thats makes the kinect not usefull
for indoor navigation.

=== Hardware
- The current batteries should be powerfull enough to power the current Willy.
- The 230 volt touchscreen in combination with the power converter is replaced by a 19v display.
- The brakes are not easy to deploy. Thats because the levers on the side of willy are to loose
to deploy the brake. We can't tight them because the screw is malformed.
- The GPS sensor and compass only work outside and are controlled using the GPSController.
- The kinect cannot be used outside. The IR camera can't handle the bright sunlight.

=== Design
- The current battery shell will not fit because of the new motorcontroller. Therefore we
created a set of new brackets to mount the 6 batteries onto the chassis.

== Navigation findings
- Move_base as of this moment is not aware of the shape of the robot. This results in issues where the robot thinks it can pass between objects or rotate while in reality it can't. It advisable to make move_base aware of the shape of the robot.
- The global planner has not been tuned yet. As of this moment it tries to create a route which is very close to the walls because it wants the fastest route. It would be better for the robot to be driving in the middle of a hallway then hug the wall. The global planner als makes very sharp corners which the robot can't handle very well. A custom planner or tweaking the standard planner can help a lot.
- The the default default planner which is currently in optimized for a robot with powered rear wheels and a steering front wheels like a car. However willy has two powered wheels which steer using differential power and two swivel wheels.

=== Social interaction
- There are a lot of ways to communicate with Willy. The ones we're using are: +
-> Leap + 
-> kinect +
-> Voice recognition +
-> TTS (Text to Speech) +
-> Lights (Led and sirene) +
-> Keyboard +
-> Mouse +
- Offline speech recognition is limited. There are a few solutions for hot-word detection like Snowboy.

