include::../Header.adoc[]

== ToDo and Advice

- Develop a roaming mode. At the moment Willy has to be given a position to drive to. In the future Willy should be able to roam around on its own without directions of humans.
- Create and maintain a social media page. To increase the media attention for Willy, it would be a nice idea to create a social media page dedicated to Willy.
This would increase the amount of attention to the 
- Develop the social interaction. There have been multiple groups that worked on the social interaction but still have not made much progress.
- Human detection. A group worked on human detection but did not fully implement it. To build a good Human detection system would make it possible to
interact with humans.
- New Design. Willy is in need of a makeover. The state of Willy at the moment is a bit messy and it would be nice to give Willy an upgrade.

=== Advice

Try to focus on 1 task instead of taking on too much. Previous groups have done this in the past only to realise that they had taken on too much.
The best course of action to avoid this and take the project step by step.