include::../Header.adoc[]

== Willy WRT
In order to let all the hardware nodes communicate between each other (and to Skylab) an OpenWRT router was used, to keep with the theme, the node is aptly named: WillyWRT. 

The router is installed on a Raspberry Pi 3b+ and OpenWRT is used as the operating system, since it is optimized to run a fully fledged network router on a low-power device. Aside from its power requirements , it has a small form-factor, and easily replaceable due to the low purchase cost.

link::https://downloads.openwrt.org/releases/[Stable releases OpenWRT]

NOTE: While in other sections it might still mention something about OpenWRT not being compatible with the RPi 3b+, as of the time of writing this note (12/02/19), OpenWRT has released (nightly) builds that run on said device. As such, a Raspberry Pi provided by Windesheim is used, and no longer needs replacing.

=== Wireless Connection

Due to safety concerns, WTR does not communicate to the Internet anymore aside from the Power Node for time synchronization via NTP and critical updates to ROS. 
Instead, a secured Wi-Fi access point was created to allow for remote control via VNC/SSH and wireless file transferring.

Like the physical connection; the wireless access point assigns dynamic IP addresses in the same range.

=== Physical connection

Ethernet cables are used in conjunction with a networking switch to connect each Raspberry Pi, the LIDAR and the Laptop(Power Node) together in a local area network contained upon WTR. Ideally, this should be airgapped to prevent unauthorized access; once the security is compromised, any malicious attacker could turn the robot into a dangerous entity.

NOTE: It is important that the laptop and the router pi are connected to the switch at a minimum. ROS requires that the network is initialized in order to run.  


=== VPN Tunnel

IMPORTANT: This might no longer function as the sixth group did not require remote access on this level, plus the router pi was since rebuilt to accomodate the new version of the raspberry pi hardware.

A reason for us to choose for OpenWRT is to use an openVPN tunnel between Skylabs PFsense firewall and Willy's LAN. Since configuring openVPN on openWRT can be challenging we have also exported the working configuration. 
link:{url}hardware_nodes/WillyWRT/backup-Export-WillyWRT-2018-12-12.tar.gz[WillyWRT current configuration.]