include::../Header.adoc[]

== Willy WRT
In order to let all the hardware nodes communicate between each other (and to Skylab) an OpenWRT router was used, named WillyWRT. 

The router is installed on a Raspberry Pi and OpenWRT is used as the hardware is easily capable of running on a low-power device. It was preferred to use another Raspberry Pi for this functionality, since aside from its power requirements, it has a small form-factor and easily replaceable as well as the low purchase cost.

link::https://downloads.openwrt.org/releases/[Stable releases OpenWRT]

NOTE:While in other section it might still mention something about OpenWRT not being compatible with the RP 3b+, as of the time of writing this note (12/02/19) OpenWRT has been updated to run on said device. As such, a Raspberry Pi provided by Windesheim is used, and no longer needs replacing.

=== Connection

We requested Windesheims ICT department to give WillyWRT Wireless access to the internet, so all peripherals can communicate with the outside world. 
The MAC-address is whitelisted and in the password documentation you can find the SSID and password. 

=== Physical

The Wireless interface connects to the SSID provided by Windesheim, the LAN interface connects to a switch and provides (static) DHCP leases to the various hardware on physical Willy. We also applied a custom etc/hosts entry to make sure the ROS master can always resolve the FQDNs and/or hardware. 

NOTE: ROS communicates via the ROS master suggest to read up on this process as well. Make sure the different hardware nodes can communicate on DNS name and IP-adress. This can take a lot of time troubleshooting. 

=== VPN Tunnel

Another reason for us to choose for OpenWRT is to use an openVPN tunnel between Skylabs PFsense firewall and Willy's LAN. Since configuring openVPN on openWRT can be challenging we have also exported the working configuration. 
link:{url}hardware_nodes/WillyWRT/backup-Export-WillyWRT-2018-12-12.tar.gz[WillyWRT current configuration.]